### PR TITLE
Adding static images hosting and resources section

### PR DESCRIPTION
**Pull request by thogiti**
## Wiki PR Checklist

- [x] Added static images instead of mermaid rendered script.
- [x] Added Resources section.
- [x] Check grammar and spelling errors locally.

### CODE REVIEW

**Comment by thogiti** [comment]
@taxmeifyoucan Updated the `ePBS.md` for hosting static images and a resources section to make the references visible.

**Comment by taxmeifyoucan** [comment]
Are you sure you don't want to use the mermaid instead? It's more effective to host than pictures and easier to edit

**Comment by thogiti** [comment]
> Are you sure you don't want to use the mermaid instead? It's more effective to host than pictures and easier to edit

I like mermaid script based rendering because Github automatically adds some zoom/pan controls and the text and objects are responsive to the device resolution. 

I will make another commit to put the mermaid code back.

**Comment by thogiti** [comment]
Added back the mermaid scripts to render PTC and PEPC workflows in this commit. 
https://github.com/eth-protocol-fellows/protocol-studies/pull/178/commits/389faa914aefd5f933c4b049036b9712665d54cb

We can close this PR (delete it) because everything is included in the epbs specs PR at https://github.com/eth-protocol-fellows/protocol-studies/pull/178

**Pull request closed without merging**
