### PR TITLE
✨ feat(Week 10D): Links

### PR DESCRIPTION
**Pull request by raxhvl**
## Wiki PR Checklist

Links updated.

### CODE REVIEW

**Comment by raxhvl** [comment]
HI @thogiti could review these jargons specific to KZG and Preconfs and them to `wordlist`?

**Comment by thogiti** [comment]
> 📄 ./docs/wiki/research/Preconfirmations/BasedSequencingPreconfs.md:

I pushed a new PR with the updated `wordlist.txt` file. https://github.com/eth-protocol-fellows/protocol-studies/pull/206

Not sure what happened and why the updated `wordlist.txt wasn't added in the previous merge. No worries. The above PR has updated wordlist.

**Comment by thogiti** [comment]
@raxhvl What is the version number of aspell on the server side?

I just saw Github action failed the spellcheck for a single word `Parallelization` but it was passing ok locally.

**Comment by thogiti** [comment]
Ok, now spellcheck is passing. https://github.com/eth-protocol-fellows/protocol-studies/pull/206

**Comment by thogiti** [comment]
> Thank you!
> 
> > I just saw Github action failed the spellcheck for a single word Parallelization but it was passing ok locally.
> 
> What caused this? Was it version diff? I believe the action uses latest version.

Here is the exact command I am running locally with all the flags:
`for f in **/*.md ; do echo $f ; aspell --lang=en_US --mode=markdown --home-dir=. --personal=wordlist.txt --ignore-case=true --camel-case list  < $f | sort | uniq -c ; done`

Here is the version I have locally:
image

**Pull request merged**
