### PR TITLE
✨ feat: Meeting #1 notes

### PR DESCRIPTION
**Pull request by raxhvl**
Please review if I have misinterpreted anything.

### CODE REVIEW

**Comment by shyam-patel-kira** [comment]
looks good to me

**Review by shyam-patel-kira — APPROVED** [review]
Approving in case, it needs to be merged

**Comment by thogiti** [comment]
Looks good. Thx @raxhvl.

**Comment by taxmeifyoucan** [comment]
Thank you so much for note taking again! Contains everything discussed, great job

**Pull request merged**
