### PR TITLE
Adding Kurtosis to Testing

### PR DESCRIPTION
**Pull request by faytey**
- [ ] Adding Kurtosis to the Testing Module in the wiki

### CODE REVIEW

**Comment by arredr2** [comment]
Cheers @faytey! I think this looks good.

**Review by arredr2 — APPROVED** [review]

**Comment by raxhvl** [comment]
Hey @faytey! Thanks for adding this. Feedback:

- Could you highlight the importance of Kurtosis in Ethereum development and testing? There is a kurtosis [package](https://github.com/kurtosis-tech/ethereum-package) for Ethereum. See this [for inspiration](https://ethereum.org/en/developers/docs/development-networks/#kurtosis).

**Comment by faytey** [comment]
> Hey @faytey! Thanks for adding this. Feedback:
> 
> * Could you highlight the importance of Kurtosis in Ethereum development and testing? There is a kurtosis [package](https://github.com/kurtosis-tech/ethereum-package) for Ethereum. See this [for inspiration](https://ethereum.org/en/developers/docs/development-networks/#kurtosis).

Hi Sir, I've made some edits

**Comment by raxhvl** [comment]
Excellent! thanks

**Review by raxhvl — APPROVED** [review]

**Pull request merged**
