### PR TITLE
Wiki Page for PBS

### PR DESCRIPTION
**Pull request by shyam-patel-kira**
Addressing #93 

- [x] Quick intro, what the page will cover
- [x] Insight into consensus layer
    - [x] Explaining role of the builder
    - [x] Explain role of the proposal
- [x] Current state
    - [x] default behavior
    - [x] PBS and relationship of relays, builders and validators
    - [ ] mevboost, documenting what is it, how it works
    - [x] issues stemming from this (security, third party dependency, censorship etc)
- [ ] Proposed solutions, current R&D
    - [ ] ePBS, inclusion lists, PEPC, etc
- [ ] Collection of resources
    - [ ] all hackmds, ethresearch posts and related articles, videos, papers you stumble upon

### CODE REVIEW

**Comment by thogiti** [comment]
@shyam-patel-kira How do I contribute to this topic/tasks? Do I pull in your pbs branch repo and submit changes to your branch? (Since this is not merged into the upstream yet.)

**Comment by taxmeifyoucan** [comment]
You can switch the PR to branch `pbs` @shyam-patel-kira

**Comment by shyam-patel-kira** [comment]
Changed the base branch to pbs

**Comment by thogiti** [comment]
Great, thx. 

Can we now do a fresh pull from the PBS branch and work on the tasks list? I see this PR is not merged yet, I am wondering if it will add more confusion to the structure of the PBS pages?

**Comment by shyam-patel-kira** [comment]
> Great, thx.
> 
> Can we now do a fresh pull from the PBS branch and work on the tasks list? I see this PR is not merged yet, I am wondering if it will add more confusion to the structure of the PBS pages?

Hey @thogiti, there are still tasks that are not completed like mev-boost and current R&D, if you'd like to add more topic to the existing PR that'd be great. I've defined a good structure for the Wiki-entry, such that anyone can contribute to it. Feel free to make a PR to my fork as well if that's needed.

I'd like to request @taxmeifyoucan, to merge this PR into the PBS branch so everyone can have the same base for future PRs

**Comment by raxhvl** [comment]
hey @shyam-patel-kira @thogiti - the branch is now merged. Feel free to checkout the branch `pbs` and add your changes.

**Pull request merged**
