### PR TITLE
🐞 fix: Content text color

### PR DESCRIPTION
**Pull request by raxhvl**
- [x] Fixes a readability issue with text on some browsers.
- [x] Typos

### CODE REVIEW

**Comment by taxmeifyoucan** [comment]
@biafra23 Can you please give one a test before we merge?

**Comment by biafra23** [comment]
How do I test this before you merge?

**Comment by raxhvl** [comment]
Preview changes on this link: https://epf-wiki-git-fix-theme-text-color-0xrahls-projects.vercel.app/

**Comment by biafra23** [comment]
Firefox on MacOS: 

The main text is fine. But the headlines are not.
image

**Comment by taxmeifyoucan** [comment]
Thanks a lot Dirk! 

@raxhvl Let's divide it into style for Hs, body, sidebar so we can define slight differences between each.

**Comment by raxhvl** [comment]
I'm unable to reproduce this on my mac + firefox setup. Here is how the production site renders: 
aKtu2PbVIzC5

**Comment by raxhvl** [comment]
@taxmeifyoucan I have adjusted the color. Headings are white, content is few shades darker. You could fine tune here:
https://github.com/eth-protocol-fellows/protocol-studies/blob/91b8d1568a6a95422336fdb779bec2ae78b9ac46/docs/assets/css/custom.css#L175-L177

Preview link: https://epf-wiki-git-fix-theme-text-color-0xrahls-projects.vercel.app/#/

**Comment by biafra23** [comment]
Looks good for me (Firefox & Chrome on macOS): 
image

**Comment by taxmeifyoucan** [comment]
Awesome, thanks a lot guys!

**Pull request merged**
