### PR TITLE
✨ feat(Theme): Fresh coat of paint

### PR DESCRIPTION
**Pull request by raxhvl**
Minimal ui tweaks for a modern look.
- New dark theme.
- Brand icon in sidebar.
- Active page highlight in sidebar.
- Prominent search bar.
- Wider tables.
- Anchor tags for headings inside wiki.

Feedbacks welcome!

new-theme

### CODE REVIEW

**Comment by taxmeifyoucan** [comment]
Thanks a lot Rahul. I will give it a proper test in local environment and maybe tweak something. 

Overall it's all great, the only thing I am not sure about is the color. Maybe we should define some style guidelines to have a standardized color pallet, similar to how ethereumorg does that

**Comment by raxhvl** [comment]
Sounds good. [colorhunt](https://colorhunt.co/) and [coolors](https://coolors.co/generate) are great resource for finding pallets.

**Comment by taxmeifyoucan** [comment]
Seems like other contributors didn't mind the purple, I changed it to a bit more neutral purple/blue with less contrast. I think we can experiment further and keep improving the CSS. One thing could be a light/dark switch although I think we can be dark only. 
image

**Comment by gorondan** [comment]
Looks good imo. Draws attention but is not heavy to the eye. Dark theme is enough, probably for this color pallette

**Pull request merged**
