### PR TITLE
Add El Architecture file for collaborating

### PR DESCRIPTION
**Pull request by SiddharthV1**

### CODE REVIEW

**Comment by SiddharthV1** [comment]
@taxmeifyoucan : I can also keep the el-architecture  file empty for now. is that is preferred ? Also I am also not sure if this should initially  be merged to main or a dedicated branch?....  I added a note there , in case someone  missed the discord message and would like to collaborate

**Comment by taxmeifyoucan** [comment]
Hey @SiddharthV1! I created `el-architecture` branch, you can change the PR to target it instead of main. You have been invited to the wiki team so you will have write access to the branch

**Comment by SiddharthV1** [comment]
Thanks @taxmeifyoucan , I accepted the invite. I can't see the new branch when I try to change the target ,I can see only main, scaling and wiki-pages. Oddly,  if I open a new PR it shows me that branch , I'll try and open a new PR targeting that branch  and then should I close this one?

**Comment by taxmeifyoucan** [comment]
I see you opened the new PR. It should be possible to redirect this one tho, not sure what's the issue. I am closing this n favor of #60

**Pull request closed without merging**
